name: fluttercode
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  get: ^4.6.5
  flutter_native_splash: ^2.2.19
  material: ^1.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/CrudeeSplash.png
  android: true
  ios: true
# flutter pub run flutter_native_splash:create


flutter:
  uses-material-design: true
